### ISSUE TITLE
Can't unpickle result objects outside MOLNs

### ISSUE THREAD

**Issue by ahellander** [ahellander/molnsutil#17]
Objects created with molnsutil, using e.g. ps.put('filaname', result) fails to unpickle outside of an MOLNs environment, due to a missing file $HOME/.molns/s3.json. (even if we install molnsutil). The actual content of the credentials file is not actually needed to parse the pickled object (that is only needed to connect to S3 or Swift) but the file must be present and be valid json to deserialize the object. 

Right now that file is created not by molnsutil, but rather by the molnsclient libraries (because the content is only know at molnsclient runtime). But we should move the logic of creating that file, or at least a template for it that will allow deserialization, to molnsutil. 

This is actually a real use case, students at the LDSA course came across this problem.

**Comment by ahellander** [comment]
This 4095fb96b691cdb54968e2b377ae03fb041ae7b3 bypasses the problem, emitting a warning wiht the instruction to create the file to be able to connect to Swift or S3. A better solution might be to try to create the file from environmental variables.

**Comment by briandrawert** [comment]
Closed in https://github.com/Molns/molnsutil/pull/3
